Uc 4
luiscarlossf/get-promo pull request #48
Opened 2018-12-04 13:09 UTC by wesleyrf10

2018-12-04 15:59 UTC, luiscarlossf commented on src/pages/profile/profile.html
> +    <ion-title>Perfil</ion-title>
Não Tem como voltar para o menu inicial!!!!

2018-12-04 16:05 UTC, luiscarlossf requested changes
Os dados não estão sendo recuperados do servidor? Acho que pra ser realmente aprovado deveria já tudo completo nessa parte.

2018-12-04 16:05 UTC, luiscarlossf commented on src/pages/profile/profile.html
> +
Não Tem como voltar para o menu inicial!!!!

2018-12-04 16:05 UTC, luiscarlossf commented on src/app/app.component.ts
> +      { title: 'EditarPerfil', component: EditProfilePage}
EditarPerfil é realmente pra tá aqui? Eu clico e não vai pra lugar nenhum

2018-12-05 08:58 UTC, wesleyrf10 commented on src/app/app.component.ts
> +      { title: 'EditarPerfil', component: EditProfilePage}
Não precisava estar aí, foi engano.

2018-12-05 11:55 UTC, luiscarlossf approved these changes

2018-12-05 11:55 UTC, luiscarlossf commented
Top, parabéns!

2018-12-05 11:55 UTC, merged